### ISSUE TITLE
我想问一下怎么用变量替换一下内容

### ISSUE THREAD

**Issue by duolabmeng6** [zcong1993/actions-ding#11]
我知道这个问题很2...但是我真不会啊 
```
    - name: 发送钉钉通知
      uses: zcong1993/actions-ding@master
      with:
        dingToken: ${{ secrets.DING_TOKEN }}
        secret: ${{ secrets.DING_SECRET }} 
        body: |
          {
            "msgtype": "link",
            "link": {
                "text": "请前往查看",
                "title": "QtEasyDesigner v0.0.1 版本已发布 ${{ env.GITHUB_ACTION_REPOSITORY }}",
                "messageUrl": "https://github.co/${{ env.GITHUB_ACTION_REPOSITORY }}/releases"
            }
          }
```
没成功

**Comment by zcong1993** [comment]
```yaml
- name: 发送钉钉通知
      uses: zcong1993/actions-ding@master
      with:
        dingToken: ${{ secrets.DING_TOKEN }}
        secret: ${{ secrets.DING_SECRET }} 
        body: |
          {
            "msgtype": "link",
            "link": {
                "text": "请前往查看",
                "title": "QtEasyDesigner v0.0.1 版本已发布 ${{github.repository}}}",
                "messageUrl": "https://github.co/${{github.repository}}/releases"
            }
          }
```
直接可以用 context 变量 https://docs.github.com/en/enterprise-server@3.2/actions/learn-github-actions/contexts#github-context
