### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by XRSecAdmin** [zcong1993/actions-ding#6]
```yaml
      - 
        name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          secret: ${{ secrets.DING_SECRET }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "{{ GITHUB_REPOSITORY }} Update Success!",
                  "title": "{{ GITHUB_REPOSITORY }}  Update Success!",
                  "picUrl": "",
                  "messageUrl": "{{ GITHUB_SERVER_URL }}/{{ GITHUB_REPOSITORY }}/"
              }
            }
```

希望能支持环境变量，这样的话通用性更强

**Comment by zcong1993** [comment]
直接可以用 context 变量 https://docs.github.com/en/enterprise-server@3.2/actions/learn-github-actions/contexts

```yaml
      - 
        name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          secret: ${{ secrets.DING_SECRET }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "${{github.repository}} Update Success!",
                  "title": "${{github.repository}} Update Success!",
                  "picUrl": "",
                  "messageUrl": "${{github.server_url}}/${{github.repository}}"
              }
            }
```
